[package]
name = "CetusClmm"
version = "1.2.0"
published-at = "0x721d950e57259cd97d41010887ab502ee7753b0a3deb4b6a80099aad0c833928"

[dependencies]
MoveSTL = { git = "https://github.com/CetusProtocol/move-stl.git", rev = "mainnet-v1.3.0", override = true }
IntegerMate = { git = "https://github.com/CetusProtocol/integer-mate.git", rev = "mainnet-v1.3.0", override = true }

[addresses]
cetusclmm = "0x1eabed72c53feb3805120a081dc15963c204dc8d091542592abaf7a35689b2fb"
