[package]
name = "arb-strategy"
version.workspace = true
edition.workspace = true

[dependencies]
arb-types.workspace = true
tracing.workspace = true
anyhow.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
base64.workspace = true
